--
-- Constants values for use with the Lua API
--

-- mapnode.h
-- Built-in Content IDs (for use with VoxelManip API)
core.CONTENT_UNKNOWN = 125
core.CONTENT_AIR     = 126
core.CONTENT_IGNORE  = 127

-- emerge.h
-- Block emerge status constants (for use with core.emerge_area)
core.EMERGE_CANCELLED   = 0
core.EMERGE_ERRORED     = 1
core.EMERGE_FROM_MEMORY = 2
core.EMERGE_FROM_DISK   = 3
core.EMERGE_GENERATED   = 4

-- constants.h
-- Size of mapblocks in nodes
core.MAP_BLOCKSIZE = 16
-- Default maximal HP of a player
core.PLAYER_MAX_HP_DEFAULT = 20
-- Default maximal breath of a player
core.PLAYER_MAX_BREATH_DEFAULT = 10

-- light.h
-- Maximum value for node 'light_source' parameter
core.LIGHT_MAX = 14

-- Sandboxy game constants

-- Player constants
PLAYER_MAX_HP_DEFAULT = 20
PLAYER_MAX_BREATH_DEFAULT = 10
PLAYER_START_HP_DEFAULT = 20
PLAYER_START_BREATH_DEFAULT = 10

-- Movement constants
PLAYER_JUMP_SPEED = 6.5
PLAYER_GRAVITY = 9.81
PLAYER_TERMINAL_VELOCITY = 100
PLAYER_WALK_SPEED = 4.0
PLAYER_CROUCH_SPEED = 1.35
PLAYER_SNEAK_SPEED = 1.5
PLAYER_RUN_SPEED = 6.0
PLAYER_LIQUID_MOVE_SPEED = 2.4
PLAYER_CLIMB_SPEED = 3.0

-- Interaction constants
PLAYER_MAX_EYE_RANGE = 10.0
PLAYER_INTERACT_RANGE = 5.0
PLAYER_PLACE_RANGE = 5.0
PLAYER_COLLECT_RANGE = 3.0
PLAYER_SELECT_BOX_LINE_WIDTH = 2

-- Tool constants
TOOL_MAX_WEAR = 65535
TOOL_WEAR_MULTIPLIER = 1

-- Node constants
NODE_MAX_LIGHT = 14
NODE_LIGHT_AMBIENT = 0
NODE_MAX_GROUPS = 32
NODE_DTIME_LIMIT = 0.2

-- Light constants
LIGHT_MAX = 14
LIGHT_SUN = 15
LIGHT_MAX_RAY = 8

-- Time constants
TIME_SPEED_MIN = 0.0
TIME_SPEED_MAX = 1000.0
TIME_SPEED_DEFAULT = 72

-- Map generation constants
MAP_BLOCKSIZE = 16
MAP_GENERATION_LIMIT = 31000
CHUNK_SIZE_LIMIT = 5
EMERGE_QUEUE_SIZE = 256
ACTIVEOBJECT_TIMEOUT = 30

-- Liquid flow constants
LIQUID_FLOW_MAX = 8
LIQUID_QUEUE_MAX_SIZE = 100
LIQUID_TICK = 0.5
WATER_ALPHA = 160
LAVA_ALPHA = 255

-- Entity constants
ENTITY_RENDERING_INCREMENT = 1.5
ENTITY_VISIBILITY_FACTOR = 1.0

-- Mapgen constants
MAPGEN_DEFAULT = "v7"
MAPGEN_VALLEYS = "valleys"
MAPGEN_CARPATHIAN = "carpathian"
MAPGEN_V5 = "v5"
MAPGEN_V6 = "v6"
MAPGEN_V7 = "v7"
MAPGEN_FRACTAL = "fractal"
MAPGEN_FLAT = "flat"
MAPGEN_SINGLENODE = "singlenode"

-- Authentication constants
AUTH_MECHANISM_FIRST_SRP = "first_srp"
AUTH_MECHANISM_SRP = "srp"
AUTH_MECHANISM_LEGACY_PASSWORD = "legacy_password"
AUTH_DEFAULT_TIMEOUT = 30

-- Privileges
PRIV_INTERACT = "interact"
PRIV_TELEPORT = "teleport"
PRIV_BRING = "bring"
PRIV_SETTIME = "settime"
PRIV_CREATIVE = "creative"
PRIV_FLY = "fly"
PRIV_FAST = "fast"
PRIV_NOCLIP = "noclip"
PRIV_GIVE = "give"
PRIV_PROTECTION_BYPASS = "protection_bypass"
PRIV_BAN = "ban"
PRIV_KICK = "kick"
PRIV_ROLLBACK = "rollback"
PRIV_PRIVS = "privs"
PRIV_BASIC_PRIVS = "interact, shout"
PRIV_ADMIN_PRIVS = "interact, shout, fly, fast, teleport, noclip, give, protection_bypass, privs"

-- Game rules
GAME_MODE_SURVIVAL = 0
GAME_MODE_CREATIVE = 1
DEFAULT_GAME_MODE = GAME_MODE_SURVIVAL
ENABLE_DAMAGE_DEFAULT = true
ENABLE_PVP_DEFAULT = true
ENABLE_TNT_DEFAULT = false
DISABLE_FIRE_DEFAULT = true

-- Return constants table
return {
    PLAYER = {
        MAX_HP = PLAYER_MAX_HP_DEFAULT,
        MAX_BREATH = PLAYER_MAX_BREATH_DEFAULT,
        START_HP = PLAYER_START_HP_DEFAULT,
        START_BREATH = PLAYER_START_BREATH_DEFAULT,
        JUMP_SPEED = PLAYER_JUMP_SPEED,
        GRAVITY = PLAYER_GRAVITY,
        TERMINAL_VELOCITY = PLAYER_TERMINAL_VELOCITY,
        WALK_SPEED = PLAYER_WALK_SPEED,
        CROUCH_SPEED = PLAYER_CROUCH_SPEED,
        SNEAK_SPEED = PLAYER_SNEAK_SPEED,
        RUN_SPEED = PLAYER_RUN_SPEED,
        LIQUID_MOVE_SPEED = PLAYER_LIQUID_MOVE_SPEED,
        CLIMB_SPEED = PLAYER_CLIMB_SPEED,
        MAX_EYE_RANGE = PLAYER_MAX_EYE_RANGE,
        INTERACT_RANGE = PLAYER_INTERACT_RANGE,
        PLACE_RANGE = PLAYER_PLACE_RANGE,
        COLLECT_RANGE = PLAYER_COLLECT_RANGE,
        SELECT_BOX_LINE_WIDTH = PLAYER_SELECT_BOX_LINE_WIDTH
    },
    TOOL = {
        MAX_WEAR = TOOL_MAX_WEAR,
        WEAR_MULTIPLIER = TOOL_WEAR_MULTIPLIER
    },
    NODE = {
        MAX_LIGHT = NODE_MAX_LIGHT,
        LIGHT_AMBIENT = NODE_LIGHT_AMBIENT,
        MAX_GROUPS = NODE_MAX_GROUPS,
        DTIME_LIMIT = NODE_DTIME_LIMIT
    },
    LIGHT = {
        MAX = LIGHT_MAX,
        SUN = LIGHT_SUN,
        MAX_RAY = LIGHT_MAX_RAY
    },
    TIME = {
        SPEED_MIN = TIME_SPEED_MIN,
        SPEED_MAX = TIME_SPEED_MAX,
        SPEED_DEFAULT = TIME_SPEED_DEFAULT
    },
    MAP = {
        BLOCKSIZE = MAP_BLOCKSIZE,
        GENERATION_LIMIT = MAP_GENERATION_LIMIT,
        CHUNK_SIZE_LIMIT = CHUNK_SIZE_LIMIT,
        EMERGE_QUEUE_SIZE = EMERGE_QUEUE_SIZE,
        ACTIVEOBJECT_TIMEOUT = ACTIVEOBJECT_TIMEOUT
    },
    LIQUID = {
        FLOW_MAX = LIQUID_FLOW_MAX,
        QUEUE_MAX_SIZE = LIQUID_QUEUE_MAX_SIZE,
        TICK = LIQUID_TICK,
        WATER_ALPHA = WATER_ALPHA,
        LAVA_ALPHA = LAVA_ALPHA
    },
    ENTITY = {
        RENDERING_INCREMENT = ENTITY_RENDERING_INCREMENT,
        VISIBILITY_FACTOR = ENTITY_VISIBILITY_FACTOR
    },
    MAPGEN = {
        DEFAULT = MAPGEN_DEFAULT,
        VALLEYS = MAPGEN_VALLEYS,
        CARPATHIAN = MAPGEN_CARPATHIAN,
        V5 = MAPGEN_V5,
        V6 = MAPGEN_V6,
        V7 = MAPGEN_V7,
        FRACTAL = MAPGEN_FRACTAL,
        FLAT = MAPGEN_FLAT,
        SINGLENODE = MAPGEN_SINGLENODE
    },
    AUTH = {
        MECHANISM_FIRST_SRP = AUTH_MECHANISM_FIRST_SRP,
        MECHANISM_SRP = AUTH_MECHANISM_SRP,
        MECHANISM_LEGACY_PASSWORD = AUTH_MECHANISM_LEGACY_PASSWORD,
        DEFAULT_TIMEOUT = AUTH_DEFAULT_TIMEOUT
    },
    PRIVS = {
        INTERACT = PRIV_INTERACT,
        TELEPORT = PRIV_TELEPORT,
        BRING = PRIV_BRING,
        SETTIME = PRIV_SETTIME,
        CREATIVE = PRIV_CREATIVE,
        FLY = PRIV_FLY,
        FAST = PRIV_FAST,
        NOCLIP = PRIV_NOCLIP,
        GIVE = PRIV_GIVE,
        PROTECTION_BYPASS = PRIV_PROTECTION_BYPASS,
        BAN = PRIV_BAN,
        KICK = PRIV_KICK,
        ROLLBACK = PRIV_ROLLBACK,
        PRIVS = PRIV_PRIVS,
        BASIC_PRIVS = PRIV_BASIC_PRIVS,
        ADMIN_PRIVS = PRIV_ADMIN_PRIVS
    },
    GAME = {
        MODE_SURVIVAL = GAME_MODE_SURVIVAL,
        MODE_CREATIVE = GAME_MODE_CREATIVE,
        DEFAULT_MODE = DEFAULT_GAME_MODE,
        ENABLE_DAMAGE_DEFAULT = ENABLE_DAMAGE_DEFAULT,
        ENABLE_PVP_DEFAULT = ENABLE_PVP_DEFAULT,
        ENABLE_TNT_DEFAULT = ENABLE_TNT_DEFAULT,
        DISABLE_FIRE_DEFAULT = DISABLE_FIRE_DEFAULT
    }
}
