.TH SANDBOXY "6" "May 2025" "Sandboxy 1.0.0" "Games"

.SH NAME
sandboxy \- A free open-source voxel game engine

.SH SYNOPSIS
.B sandboxy
[\fI\,OPTIONS\/\fR]

.SH DESCRIPTION
Sandboxy is a free open-source voxel game engine with easy modding capabilities.
Build anything you can imagine with simple building blocks in a vast world.

.SH OPTIONS
.TP
\fB\-\-help\fR
Print allowed options and exit
.TP
\fB\-\-version\fR
Print version information and exit
.TP
\fB\-\-config\fR <value>
Load configuration from specified file
.TP
\fB\-\-port\fR <value>
Set network port (UDP) to use
.TP
\fB\-\-name\fR <value>
Set player name
.TP
\fB\-\-gameid\fR <value>
Request game by its name
.TP
\fB\-\-worldname\fR <value>
Set world path by name
.TP
\fB\-\-world\fR <value>
Set world path

.SH FILES
.TP
~/.local/share/sandboxy/
User configuration directory
.TP
~/.local/share/sandboxy/worlds/
Game worlds
.TP
~/.local/share/sandboxy/mods/
User-installed mods
.TP
~/.local/share/sandboxy/textures/
User-installed texture packs

.SH BUGS
Please report bugs at:
.br
https://github.com/sandboxyorg/sandboxy/issues

.SH AUTHOR
Copyright \(co 2025 Sandboxy Developers
.PP
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
