.TH SANDBOXYSERVER "6" "May 2025" "sandboxyserver" "Games"
.SH NAME
sandboxyserver \- Dedicated server for Sandboxy
.SH SYNOPSIS
.B sandboxyserver
[\fBSERVER OPTIONS\fR]
[\fBCOMMON OPTIONS\fR]
[\fBWORLD PATH\fR]
.SH DESCRIPTION
.B Sandboxy
is a voxel game engine with easy modding and game creation.
.B sandboxyserver
is a dedicated server for Sandboxy.

